# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d3f47de8971b31fa92d9dea1f0dd52ec217420c767538183692cfabdaba3b3e16be39ff49db3289ff8fed52ec091d7c4c41f6bea7431fc6a62fbbb510afc6869

test:
  secret_key_base: d07f99ecc80b1cd0684e24a66e679d35b01b90ee5d8e94744bdae5e9ce3182538f810da24b91bfbf89a1e51ab935cf8e46bd098574de511afc6757c69b30673f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
